class SourceData():
    def __init__(self):
        self.name = ''
        self.RA = 0.0        # Right Ascension (J2000)
        self.dec = 0.0       # Declination (J2000)
        self.rn = 0          # Running Number
        self.spt = 0.0
        self.eunc = 0.0
        self.lunc = 0.0
        self.Aj_SP = 0.0
        self.dAj_SP = 0.0
        self.Aj_SP_SN = 0.0
        self.Aj_CTT = 0.0
        self.dAJ_CTT = 0.0
        self.Aj_tweak = 0.0
        self.IRAC_alpha = 0.0
        self.c2d_alpha = 0.0
        self.c2d_dalpha = 0.0
        self.c2d_av = 0.0
        self.c2d_dav = 0.0
        self.dkbs = 0.0   # K-band slope difference
        self.rk = 0.0
        self.drk = 0.0
        self.rh = 0.0         # Photometrically computed H-band veiling
        self.drh = 0.0
        self.rj = 0.0         # Photometrically computed J-band veiling
        self.drj = 0.0
        self.lum = 0.0        # Luminosity (Log L/Lsun)
        self.ew_pab = 0.0     # Equivalent Width of Paschen Beta (Angstrom)
        self.d_ew_pab = 0.0   # Error in ew_pab
        self.f_pab = 0.0      # Dereddened flux in Paschen Beta line
        self.d_f_pab = 0.0    # Error in f_pab
        self.lacc_pab = 0.0   # Accretion Luminosity from Paschen Beta (Lsun)
        self.d_lacc_pab = 0.0 # Error in lacc_pab
        self.ew_brg = 0.0     # Equivalent Width of Brackett Gamma (Angstrom)
        self.d_ew_brg = 0.0   # Error in ew_brg
        self.f_brg = 0.0      # Dereddened flux in Brackett Gamma line
        self.d_f_brg = 0.0    # Error in f_brg
        self.lacc_brg = 0.0   # Accretion Luminosity from Brackett Gamma (Lsun)
        self.d_lacc_brg = 0.0 # Error in lacc_brg
        self.log_g = 0.0      # Surface gravity (from BCAH Tracks)
        self.mass = 0.0       # Mass of YSO (Solar Masses)
        self.age = 0.0        # Age of YSO (Myr)
        self.mdot_pab = 0.0   # Mass Accretion Rate (from Paschen Beta)
        self.mdot_brg = 0.0   # Mass Accretion Rate (from Brackett Gamma)
        self.d_mdot_pab = 0.0 # Error in mdot (from Paschen Beta)
        self.d_mdot_brg = 0.0 # Error in mdot (from Brackett Gamma)
        self.hyd_R = 0.0      # Ratio of PaB/BrG hydrogen emission lines
        self.binary = False
        self.Jmag = 0.0
        self.dJ = 0.0
        self.Hmag = 0.0
        self.dH = 0.0
        self.Kmag = 0.0
        self.dK = 0.0
        self.IRAC1 = 0.0
        self.dIRAC1 = 0.0
        self.IRAC2 = 0.0
        self.dIRAC2 = 0.0
        self.IRAC3 = 0.0
        self.dIRAC3 = 0.0
        self.IRAC4 = 0.0
        self.dIRAC4 = 0.0
        self.MIPS1 = 0.0
        self.dMIPS1 = 0.0
        self.MIPS2 = 0.0
        self.dMIPS2 = 0.0
        self.SXD_clean = ''
        self.LXD_clean = ''
        self.IRS_clean = ''
        self.SXD_flat = ''
        self.LXD_flat = ''
        self.IRS_flat = ''
